version: '3.7'
services:
  scrapper:
    container_name: scrapper
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - default

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - scrapper:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  scrapper: